"use client";

import { TableOfContents } from "@/docs/components/table-of-contents";
import { CodeBlock } from "@/docs/components/code-block";
import { Alert, AlertDescription, AlertTitle } from "@/docs/components/ui/alert";
import { Cpu, Shield, Key, FileCode } from "lucide-react";

const tocItems = [
  { id: "overview", title: "💡 Overview", level: 2 },
  { id: "client-manifest-plugin", title: "⚛️ 1. react-client-manifest-plugin.mjs", level: 2 },
  { id: "server-functions-plugin", title: "🔒 2. server-functions-plugin.mjs", level: 2 },
];

export default function Page() {
  return (
    <div className="flex-1 flex flex-col xl:flex-row w-full max-w-[100vw]">
      <main className="flex-1 py-6 lg:py-8 w-full min-w-0">
        <div className="container max-w-4xl px-4 md:px-6 mx-auto">
          {/* Header */}
          <div className="mb-8 space-y-4">
            <div className="flex items-center space-x-2">
              <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-yellow-600 dark:text-yellow-500">
                3. Core RSC Plugins
              </h1>
            </div>
            <p className="text-xl text-muted-foreground leading-relaxed">
              Explore how Dinou captures client component boundaries and strips Server Actions code using custom compile plugins.
            </p>
          </div>

          <div className="prose prose-slate dark:prose-invert max-w-none w-full break-words">
            <blockquote>
              <strong>Key Files Analyzed:</strong> <br />
              • Client compiler: <code>./dinou/esbuild/plugins-esbuild/react-client-manifest-plugin.mjs</code> <br />
              • Actions compiler: <code>./dinou/esbuild/plugins-esbuild/server-functions-plugin.mjs</code>
            </blockquote>

            {/* OVERVIEW */}
            <section id="overview">
              <h2>💡 Overview</h2>
              <p>
                React Server Components split the compilation graph: components are either server-only or client-only. Dinou implements custom loaders to build hydration boundaries and prevent server action code leakage.
              </p>
            </section>

            <hr className="my-8" />

            {/* CLIENT MANIFEST PLUGIN */}
            <section id="client-manifest-plugin">
              <h2>⚛️ 1. <code>react-client-manifest-plugin.mjs</code></h2>
              <p>
                Maps client components during the compilation end phase.
              </p>
              
              <h3>Execution Mechanics</h3>
              <p>
                Inside <code>build.onEnd()</code>, the plugin parses the output map generated by esbuild (<code>result.metafile.outputs</code>) and performs the following checks:
              </p>
              <ol>
                <li>Filters out non-JavaScript entries or assets (like CSS / images).</li>
                <li>Reads the original component source file from disk.</li>
                <li>Checks if the file begins with the <code>"use client"</code> directive.</li>
                <li>If verified, it resolves the exported module names using a parse helper (<code>parseExports</code>).</li>
                <li>Maps the export references to the final compiled bundle filename and saves them inside `react-client-manifest.json`:</li>
              </ol>

              <div className="not-prose my-4">
                <CodeBlock language="json">{`{
  "file:///c:/project/src/components/Counter.tsx": {
    "id": "/Counter-a1b2c3d4.js"
  }
}`}</CodeBlock>
              </div>
              <p>
                When rendering server components, the Node server reads this mapping file to inject the correct script tags into the browser HTML document, preventing hydration mismatch errors.
              </p>
            </section>

            <hr className="my-8" />

            {/* SERVER FUNCTIONS PLUGIN */}
            <section id="server-functions-plugin">
              <h2>🔒 2. <code>server-functions-plugin.mjs</code></h2>
              <p>
                This plugin compiles and secures Server Actions (<code>"use server"</code>). It replaces server-side code with client-side proxies and builds a whitelist to secure the execution endpoint.
              </p>

              <h3>Step 1: Client Proxy Replacement</h3>
              <p>
                When compiling client assets, the loader intercepts files containing the <code>"use server"</code> directive (<code>build.onLoad</code>). Instead of compiling database queries or secret keys, it replaces the entire code body with a fetch proxy:
              </p>
              <div className="not-prose my-4">
                <CodeBlock language="javascript">{`build.onLoad({ filter: /\\.[jt]sx?$/ }, async (args) => {
  const code = await fs.readFile(args.path, "utf8");
  if (!useServerRegex.test(code.trim())) return null;

  const exports = parseExports(code);
  const relativePath = path.relative(root, args.path).replace(/\\\\/g, "/");
  const fileUrl = \`file:///\${relativePath}\`;

  // Generate proxy wrapper
  let proxyCode = \`import { createServerFunctionProxy } from "/__SERVER_FUNCTION_PROXY__";\\n\`;
  for (const exp of exports) {
    const key = exp === "default" ? \`\${fileUrl}#default\` : \`\${fileUrl}#\${exp}\`;
    if (exp === "default") {
      proxyCode += \`export default createServerFunctionProxy(\${JSON.stringify(key)});\n\`;
    } else {
      proxyCode += \`export const \${exp} = createServerFunctionProxy(\${JSON.stringify(key)});\n\`;
    }
  }
  return { contents: proxyCode, loader: "js" }; // client bundle only receives fetch handles
});`}</CodeBlock>
              </div>

              <h3>Step 2: Sign Action Whitelist Manifest</h3>
              <p>
                In the compilation end phase (<code>build.onEnd</code>), it converts collected server function maps into a whitelist and writes it to <code>server-functions-manifest.json</code>:
              </p>
              <div className="not-prose my-4">
                <CodeBlock language="json">{`{
  "src/actions/users.ts": [
    "loginUser",
    "logoutUser"
  ]
}`}</CodeBlock>
              </div>
              <p>
                When a client calls an action, the production Express server validates the incoming request payload against this manifest. If the requested action isn't listed, the server rejects the query, protecting the endpoint from unauthorized executions.
              </p>
            </section>
          </div>
        </div>
      </main>

      <aside className="hidden xl:block w-64 pl-8 py-6 lg:py-8 shrink-0">
        <div className="sticky top-20">
          <TableOfContents items={tocItems} />
        </div>
      </aside>
    </div>
  );
}
