"use client";

import { TableOfContents } from "@/docs/components/table-of-contents";
import { CodeBlock } from "@/docs/components/code-block";
import { Shield } from "lucide-react";

const tocItems = [
  { id: "overview", title: "💡 Overview", level: 2 },
  { id: "server-functions-flow", title: "📊 Server Functions Flow", level: 2 },
  { id: "code-loader", title: "⚙️ server-functions-loader.js Walkthrough", level: 2 },
  { id: "code-plugin", title: "⚙️ server-functions-plugin.js Walkthrough", level: 2 },
];

const SERVER_FUNCTIONS_WEBPACK_DIAGRAM = `graph TD
    Start[server-functions-loader.js] --> Check{Contains 'use server'?}
    Check -->|No| Pass[Pass original source]
    Check -->|Yes| Parse[parseExports exports]
    
    Parse --> Proxy[Generate dynamic loadProxy function]
    Proxy --> EmitTemp[this.emitFile temporary server-functions/file.json]
    EmitTemp --> Return[Return client-side fetch proxy exports]
    
    Return --> Plugin[ServerFunctionsPlugin.apply: processAssets stage]
    Plugin --> ReplacePlaceholder[Replace __SERVER_FUNCTION_PROXY__ placeholder with hashed file path]
    ReplacePlaceholder --> Merge[Read all server-functions/*.json & merge exports]
    Merge --> DeleteTemp[Delete temporary files from compiler outputs]
    DeleteTemp --> WriteManifest[Write server-functions-manifest.json]`;

const LOADER_CODE = `const path = require("path");

const { normalizePathCase } = require("../../core/path-utils.js");
const parseExports = require("../../core/parse-exports.js");
const { useServerRegex } = require("../../constants.js");

module.exports = function (source) {
  let hasUseServer = false;

  if (useServerRegex.test(source)) {
    hasUseServer = true;
  }

  if (!hasUseServer) return source;

  const exports = parseExports(source);
  if (exports.length === 0) return source;

  // Build IDs
  const moduleId = this.resourcePath;
  const relativePath = path.relative(
    normalizePathCase(process.cwd()),
    normalizePathCase(moduleId)
  );
  const normalizedPath = relativePath.replace(/\\\\/g, "/");

  const fileUrl = \`file:///\${normalizedPath}\`;

  //
  // IMPORTANT: dynamic import instead of static import
  //
  // Webpack will NOT try to resolve "__SERVER_FUNCTION_PROXY__"
  // as a module → it will remain a string → replaced later → browser loads it.
  //

  let proxyCode = \`
const loadProxy = new Function('return import("/"+"__SERVER_FUNCTION_PROXY__")');
\`;

  for (const exp of exports) {
    const key = exp === "default" ? \`\${fileUrl}#default\` : \`\${fileUrl}#\${exp}\`;

    if (exp === "default") {
      proxyCode += \`
export default (...args) =>
  loadProxy().then(mod =>
    (mod.default ?? mod ?? window.__SERVER_FUNCTION_PROXY_LIB__).createServerFunctionProxy(\${JSON.stringify(
        key,
      )})(...args)
  );
\`;
    } else {
      proxyCode += \`
export const \${exp} = (...args) =>
  loadProxy().then(mod => (mod.default ?? mod ?? window.__SERVER_FUNCTION_PROXY_LIB__).createServerFunctionProxy(\${JSON.stringify(
        key,
      )})(...args)
  );
\`;
    }
  }

  // Emit manifest entry
  const manifestEntry = {
    path: normalizedPath,
    exports: exports,
  };

  this.emitFile(
    \`server-functions/\${normalizedPath}.json\`,
    JSON.stringify(manifestEntry, null, 2),
  );

  return proxyCode;
};`;

const PLUGIN_CODE = `const manifestGeneratorPlugin = require("./manifest-generator-plugin");

class WebpackServerFunctionsPluginSimple {
  constructor() {
    this.serverFunctions = new Map();
  }

  apply(compiler) {
    const { webpack } = compiler;
    const { Compilation, sources } = webpack;

    // Collect files generated by the loader
    compiler.hooks.thisCompilation.tap(
      "WebpackServerFunctionsPluginSimple",
      (compilation) => {
        compilation.hooks.processAssets.tap(
          {
            name: "WebpackServerFunctionsPluginSimple",
            stage: Compilation.PROCESS_ASSETS_STAGE_REPORT,
          },
          (assets) => {
            // 1. Replace placeholder
            const manifest = manifestGeneratorPlugin.manifestData;
            const hashedPath = manifest["serverFunctionProxy.js"] || "serverFunctionProxy.js";

            for (const [filename, asset] of Object.entries(assets)) {
              if (filename.endsWith(".js")) {
                let code = asset.source();
                if (code.includes("__SERVER_FUNCTION_PROXY__")) {
                  code = code.replace(/__SERVER_FUNCTION_PROXY__/g, hashedPath);
                  compilation.updateAsset(
                    filename,
                    new sources.RawSource(code)
                  );
                }
              }
            }

            // 2. Collect all server function files
            const serverFunctionsManifest = {};

            for (const [filename, asset] of Object.entries(assets)) {
              if (
                filename.startsWith("server-functions/") &&
                filename.endsWith(".json")
              ) {
                try {
                  const content = asset.source();
                  const entry = JSON.parse(content);
                  serverFunctionsManifest[entry.path] = entry.exports;

                  // Delete this temporary file
                  delete assets[filename];
                } catch (e) {
                  // Ignore parsing errors
                }
              }
            }

            // 3. Generate final manifest
            const manifestContent = JSON.stringify(
              serverFunctionsManifest,
              null,
              2
            );
            compilation.emitAsset(
              "server-functions-manifest.json",
              new sources.RawSource(manifestContent)
            );
          }
        );
      }
    );
  }
}

module.exports = WebpackServerFunctionsPluginSimple;`;

export default function Page() {
  return (
    <div className="flex-1 flex flex-col xl:flex-row w-full max-w-[100vw]">
      <main className="flex-1 py-6 lg:py-8 w-full min-w-0">
        <div className="container max-w-4xl px-4 md:px-6 mx-auto">
          {/* Header */}
          <div className="mb-8 space-y-4">
            <div className="flex items-center space-x-2">
              <Shield className="h-6 w-6 text-primary text-cyan-600 dark:text-cyan-500" />
              <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
                Server Functions Loader & Plugin
              </h1>
            </div>
            <p className="text-xl text-muted-foreground leading-relaxed">
              Analyze the inner workings of Webpack's module transforms for parsing Server Functions and compiling secure whitelist manifests.
            </p>
          </div>

          <div className="prose prose-slate dark:prose-invert max-w-none w-full break-words">
            <blockquote>
              <strong>Key Files Location:</strong> <br />
              • Loader transform: <code>./dinou/webpack/loaders/server-functions-loader.js</code> <br />
              • Aggregation plugin: <code>./dinou/webpack/plugins/server-functions-plugin.js</code>
            </blockquote>

            {/* OVERVIEW */}
            <section id="overview">
              <h2>💡 Overview</h2>
              <p>
                Server Functions represent endpoints executing database queries or handling credentials. Webpack compiles client bundles, meaning server components code must be stripped and replaced with client-side fetch proxies.
              </p>
              <p>
                Dinou achieves this using a custom Webpack loader to replace modules containing <code>"use server"</code> with fetch skeletons, and a custom compilation plugin to aggregate the exported functions into <code>server-functions-manifest.json</code>.
              </p>
            </section>

            <hr className="my-8" />

            {/* SERVER FUNCTIONS FLOW */}
            <section id="server-functions-flow">
              <h2>📊 Server Functions Flow</h2>
              <p>
                The flowchart below shows how Server Functions are stripped, proxied, and whitelisted during Webpack compiles:
              </p>
              <div className="not-prose my-4">
                <CodeBlock language="mermaid" minWidth="650px">{SERVER_FUNCTIONS_WEBPACK_DIAGRAM}</CodeBlock>
              </div>
            </section>

            <hr className="my-8" />

            {/* CODE WALKTHROUGH LOADER */}
            <section id="code-loader">
              <h2>⚙️ server-functions-loader.js Walkthrough</h2>
              <p>
                Below is the full code of the custom loader that strips code bodies and generates fetch proxies:
              </p>
              <div className="not-prose my-4">
                <CodeBlock language="javascript">{LOADER_CODE}</CodeBlock>
              </div>
            </section>

            <hr className="my-8" />

            {/* CODE WALKTHROUGH PLUGIN */}
            <section id="code-plugin">
              <h2>⚙️ server-functions-plugin.js Walkthrough</h2>
              <p>
                Below is the full code of the Webpack plugin that aggregates whitelisted functions and cleans temporary assets:
              </p>
              <div className="not-prose my-4">
                <CodeBlock language="javascript">{PLUGIN_CODE}</CodeBlock>
              </div>
            </section>
          </div>
        </div>
      </main>

      <aside className="hidden xl:block w-64 pl-8 py-6 lg:py-8 shrink-0">
        <div className="sticky top-20">
          <TableOfContents items={tocItems} />
        </div>
      </aside>
    </div>
  );
}
